# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-06 07:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20181105_2119'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': '评论/回复', 'verbose_name_plural': '评论/回复'},
        ),
        migrations.AddField(
            model_name='comment',
            name='restore',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Comment', verbose_name='回复对象'),
        ),
        migrations.AddField(
            model_name='comment',
            name='restore_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='restore', to=settings.AUTH_USER_MODEL, verbose_name='回复用户'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='news_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='app.Content', verbose_name='评论文章'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to=settings.AUTH_USER_MODEL, verbose_name='评论作者'),
        ),
    ]
